CREATE TABLE CATEGORIA (
  idCATEGORIA INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  Nombre VARCHAR(25) NULL,
  Descripcion VARCHAR(25) NULL,
  PRIMARY KEY(idCATEGORIA)
);

CREATE TABLE CLIENTE (
  idCLIENTE INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  idUBIGEO INTEGER UNSIGNED NOT NULL,
  Nombre VARCHAR(10) NULL,
  Apellido_P VARCHAR(10) NULL,
  Apellido_M VARCHAR(10) NULL,
  DNI VARCHAR(10) NULL,
  Telefono VARCHAR(10) NULL,
  Direccion VARCHAR(20) NULL,
  Ruc VARCHAR(15) NULL,
  Razon_Social VARCHAR(20) NULL,
  PRIMARY KEY(idCLIENTE)
);

CREATE TABLE COMPRA (
  idCOMPRA INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  idEMPLEADO INTEGER UNSIGNED NOT NULL,
  idPROVEEDOR INTEGER UNSIGNED NOT NULL,
  Fecha DATE NULL,
  Subtotal DOUBLE NULL,
  Total DOUBLE NULL,
  igv DOUBLE NULL,
  PRIMARY KEY(idCOMPRA)
);

CREATE TABLE COMPROBANTE (
  idCOMPROBANTE INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  idPEDIDO INTEGER UNSIGNED NOT NULL,
  idCLIENTE INTEGER UNSIGNED NOT NULL,
  idEMPLEADO INTEGER UNSIGNED NOT NULL,
  Subtotal DOUBLE NULL,
  Total DOUBLE NULL,
  Fecha DATE NULL,
  Tipo_Comprobante VARCHAR(10) NULL,
  Nro_Comprobante  NUMERIC(10) NULL,
  Serie NUMERIC(10) NULL,
  igv DOUBLE NULL,
  PRIMARY KEY(idCOMPROBANTE)
);

CREATE TABLE DETALLE_C (
  idCOMPROBANTE INTEGER UNSIGNED NOT NULL,
  idPRODUCTO INTEGER UNSIGNED NOT NULL,
  Precio_U DOUBLE NULL,
  Precio_M DOUBLE NULL,
  Precio_F DOUBLE NULL,
  Cantidad_U NUMERIC(10) NULL,
  Cantidad_M NUMERIC(10) NULL,
  Cantidad_F NUMERIC(10) NULL
);

CREATE TABLE DETALLE_P (
  idDETALLE_P INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  idCOMPRA INTEGER UNSIGNED NOT NULL,
  idPRODUCTO INTEGER UNSIGNED NOT NULL,
  Fecha DATE NULL,
  Precio_U DOUBLE NULL,
  Precio_M DOUBLE NULL,
  Precio_F DOUBLE NULL,
  Cantidad NUMERIC(10) NULL,
  PRIMARY KEY(idDETALLE_P)
);

CREATE TABLE EMPLEADO (
  idEMPLEADO INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  idUBIGEO INTEGER UNSIGNED NOT NULL,
  Nombre VARCHAR(10) NULL,
  Apellido_P VARCHAR(10) NULL,
  Apellido_M VARCHAR(10) NULL,
  Direccion VARCHAR(50) NULL,
  Telefono VARCHAR(20) NULL,
  DNI VARCHAR(20) NULL,
  Sexo VARCHAR(20) NULL,
  Fecha_Nacimiento DATE NULL,
  Fecha_Inicio DATE NULL,
  Fecha_Final DATE NULL,
  PRIMARY KEY(idEMPLEADO)
);

CREATE TABLE PEDIDO (
  idPEDIDO INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  idEMPLEADO INTEGER UNSIGNED NOT NULL,
  idCLIENTE INTEGER UNSIGNED NOT NULL,
  Fecha_Pedido DATE NULL,
  Fecha_Entrega DATE NULL,
  PRIMARY KEY(idPEDIDO)
);

CREATE TABLE PEDIDO_has_PRODUCTO (
  idPEDIDO INTEGER UNSIGNED NOT NULL,
  idPRODUCTO INTEGER UNSIGNED NOT NULL,
  Cantidad NUMERIC(10) NULL,
  Precio DOUBLE NULL,
  PRIMARY KEY(idPEDIDO, idPRODUCTO)
);

CREATE TABLE PRIVILEGIO (
  idPRIVILEGIO INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  Nombre VARCHAR(25) NULL,
  Url VARCHAR(25) NULL,
  Estado VARCHAR(25) NULL,
  id_padre VARCHAR(25) NULL,
  PRIMARY KEY(idPRIVILEGIO)
);

CREATE TABLE PRIVILEGIO_has_EMPLEADO (
  idEMPLEADO INTEGER UNSIGNED NOT NULL,
  idPRIVILEGIO INTEGER UNSIGNED NOT NULL,
  Fecha DATE NULL,
  PRIMARY KEY(idEMPLEADO, idPRIVILEGIO)
);

CREATE TABLE PRODUCTO (
  idPRODUCTO INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  idCATEGORIA INTEGER UNSIGNED NOT NULL,
  Nombre_Pro VARCHAR(25) NULL,
  Descripcion VARCHAR(20) NULL,
  Estado VARCHAR(15) NULL,
  Precio_U DOUBLE NULL,
  Precio_M DOUBLE NULL,
  Precio_F DOUBLE NULL,
  Color VARCHAR(25) NULL,
  Stock_U NUMERIC(10) NULL,
  Stock_M NUMERIC(14) NULL,
  Stock_F NUMERIC(10) NULL,
  PRIMARY KEY(idPRODUCTO)
);

CREATE TABLE PROVEEDOR (
  idPROVEEDOR INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  idUBIGEO INTEGER UNSIGNED NOT NULL,
  Razon_Social VARCHAR(25) NULL,
  Direccion VARCHAR(50) NULL,
  Telefono VARCHAR(15) NULL,
  Ruc VARCHAR(15) NULL,
  Fax VARCHAR(15) NULL,
  Email VARCHAR(25) NULL,
  PRIMARY KEY(idPROVEEDOR)
);

CREATE TABLE UBIGEO (
  idUBIGEO INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  Pais VARCHAR(10) NULL,
  Provincia VARCHAR(15) NULL,
  Distrito VARCHAR(15) NULL,
  PRIMARY KEY(idUBIGEO)
);


